---
title: "Average number of murder indicator per city in Rio Grande do Sul"
author: "Matheus Souza"
date: "November 2017"
output:
  pdf_document:
    number_sections: yes
  html_document: default
geometry: margin=1.5in, top=0.5in, bottom=0.5in
---

# Installing Section 
 

```{r message=FALSE, warning= FALSE}


install.packages("ggplot2", repos="http://cran.rstudio.com/")
install.packages("tidyverse", repos="http://cran.rstudio.com/")
install.packages("reshape", repos="http://cran.rstudio.com/")
```





```{r message=FALSE, warning= FALSE}


library(ggplot2)
library(dplyr)
library(magrittr)
library(tidyr)
library(readr)
library(reshape)






df_list <- list()

for (y in 2002:2016){
  URL = paste0("https://raw.githubusercontent.com/mmsouza/lps/master/Final%20Task/fee-",as.character(y),"-mun-indicadores-criminais-homicidio-doloso-103597.csv")
  aux= y-2001
  df_list[[aux]] <- read_delim(URL, delim=",")
  colnames(df_list[[aux]])[5] <- "Homi_Count"
  df_list[[aux]]<-df_list[[aux]] %>% mutate(ano= y)
  
  }

data <- merge_recurse(df_list)

data$Homi_Count <- as.numeric(data$Homi_Count)


```

```{r}

data %>% select(Homi_Count,ano) %>% group_by(ano) %>% filter(Homi_Count <100)%>%  do(b = t.test(.$Homi_Count,conf.level=0.95)) %>%  
  mutate( media = unname(b$estimate) ,maxx = c(b$conf.int[2]) ,minn = c(b$conf.int[1])) %>% ggplot(aes(x=ano, y=media)) + geom_errorbar(aes(ymin=minn, ymax=maxx), width=.1) +geom_point() +scale_y_continuous(limits = c(0,17),breaks = seq(0, 18, by = 1)) + scale_x_continuous(limits = c(2001.8,2017),breaks = seq(2002, 2016, by = 1))

df_2015 <- data %>% filter(ano ==2015)
df_2014 <- data %>% filter(ano ==2014)
t.test(df_2014$Homi_Count,df_2015$Homi_Count,conf.level=0.95, alternative = "greater")





```


